# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/its2019/its2019g25

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/its2019/its2019g25

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/its2019/its2019g25/CMakeFiles /home/its2019/its2019g25/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/its2019/its2019g25/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen
.PHONY : doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) -f CMakeFiles/doxygen.dir/build.make CMakeFiles/doxygen.dir/build
.PHONY : doxygen/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f utils/CMakeFiles/utils.dir/build.make utils/CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named ascon

# Build rule for target.
ascon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ascon
.PHONY : ascon

# fast build rule for target.
ascon/fast:
	$(MAKE) -f ascon/CMakeFiles/ascon.dir/build.make ascon/CMakeFiles/ascon.dir/build
.PHONY : ascon/fast

#=============================================================================
# Target rules for targets named isap

# Build rule for target.
isap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isap
.PHONY : isap

# fast build rule for target.
isap/fast:
	$(MAKE) -f isap/CMakeFiles/isap.dir/build.make isap/CMakeFiles/isap.dir/build
.PHONY : isap/fast

#=============================================================================
# Target rules for targets named ecc_lib

# Build rule for target.
ecc_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ecc_lib
.PHONY : ecc_lib

# fast build rule for target.
ecc_lib/fast:
	$(MAKE) -f ecclib/CMakeFiles/ecc_lib.dir/build.make ecclib/CMakeFiles/ecc_lib.dir/build
.PHONY : ecc_lib/fast

#=============================================================================
# Target rules for targets named primitives

# Build rule for target.
primitives: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 primitives
.PHONY : primitives

# fast build rule for target.
primitives/fast:
	$(MAKE) -f tls/CMakeFiles/primitives.dir/build.make tls/CMakeFiles/primitives.dir/build
.PHONY : primitives/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f tls/CMakeFiles/server.dir/build.make tls/CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f tls/CMakeFiles/client.dir/build.make tls/CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named valgrind_test_task2_custom

# Build rule for target.
valgrind_test_task2_custom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_task2_custom
.PHONY : valgrind_test_task2_custom

# fast build rule for target.
valgrind_test_task2_custom/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_task2_custom.dir/build.make tls/tests/CMakeFiles/valgrind_test_task2_custom.dir/build
.PHONY : valgrind_test_task2_custom/fast

#=============================================================================
# Target rules for targets named valgrind_test_task2_custom_xml

# Build rule for target.
valgrind_test_task2_custom_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_task2_custom_xml
.PHONY : valgrind_test_task2_custom_xml

# fast build rule for target.
valgrind_test_task2_custom_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_task2_custom_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_task2_custom_xml.dir/build
.PHONY : valgrind_test_task2_custom_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_handshake

# Build rule for target.
valgrind_test_tls_handshake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_handshake
.PHONY : valgrind_test_tls_handshake

# fast build rule for target.
valgrind_test_tls_handshake/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_handshake.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_handshake.dir/build
.PHONY : valgrind_test_tls_handshake/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_handshake_xml

# Build rule for target.
valgrind_test_tls_handshake_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_handshake_xml
.PHONY : valgrind_test_tls_handshake_xml

# fast build rule for target.
valgrind_test_tls_handshake_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_handshake_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_handshake_xml.dir/build
.PHONY : valgrind_test_tls_handshake_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_record_layer

# Build rule for target.
valgrind_test_tls_record_layer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_record_layer
.PHONY : valgrind_test_tls_record_layer

# fast build rule for target.
valgrind_test_tls_record_layer/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_record_layer.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_record_layer.dir/build
.PHONY : valgrind_test_tls_record_layer/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_record_layer_xml

# Build rule for target.
valgrind_test_tls_record_layer_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_record_layer_xml
.PHONY : valgrind_test_tls_record_layer_xml

# fast build rule for target.
valgrind_test_tls_record_layer_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_record_layer_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_record_layer_xml.dir/build
.PHONY : valgrind_test_tls_record_layer_xml/fast

#=============================================================================
# Target rules for targets named test_tls_record_layer

# Build rule for target.
test_tls_record_layer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tls_record_layer
.PHONY : test_tls_record_layer

# fast build rule for target.
test_tls_record_layer/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_tls_record_layer.dir/build.make tls/tests/CMakeFiles/test_tls_record_layer.dir/build
.PHONY : test_tls_record_layer/fast

#=============================================================================
# Target rules for targets named valgrind_test_ecdh

# Build rule for target.
valgrind_test_ecdh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_ecdh
.PHONY : valgrind_test_ecdh

# fast build rule for target.
valgrind_test_ecdh/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_ecdh.dir/build.make tls/tests/CMakeFiles/valgrind_test_ecdh.dir/build
.PHONY : valgrind_test_ecdh/fast

#=============================================================================
# Target rules for targets named valgrind_test_ecdh_xml

# Build rule for target.
valgrind_test_ecdh_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_ecdh_xml
.PHONY : valgrind_test_ecdh_xml

# fast build rule for target.
valgrind_test_ecdh_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_ecdh_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_ecdh_xml.dir/build
.PHONY : valgrind_test_ecdh_xml/fast

#=============================================================================
# Target rules for targets named test_ecdh

# Build rule for target.
test_ecdh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ecdh
.PHONY : test_ecdh

# fast build rule for target.
test_ecdh/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_ecdh.dir/build.make tls/tests/CMakeFiles/test_ecdh.dir/build
.PHONY : test_ecdh/fast

#=============================================================================
# Target rules for targets named playback

# Build rule for target.
playback: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 playback
.PHONY : playback

# fast build rule for target.
playback/fast:
	$(MAKE) -f tls/tests/CMakeFiles/playback.dir/build.make tls/tests/CMakeFiles/playback.dir/build
.PHONY : playback/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_6

# Build rule for target.
valgrind_test_tls_aes128gcm_6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_6
.PHONY : valgrind_test_tls_aes128gcm_6

# fast build rule for target.
valgrind_test_tls_aes128gcm_6/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_6.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_6.dir/build
.PHONY : valgrind_test_tls_aes128gcm_6/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_6_xml

# Build rule for target.
valgrind_test_tls_aes128gcm_6_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_6_xml
.PHONY : valgrind_test_tls_aes128gcm_6_xml

# fast build rule for target.
valgrind_test_tls_aes128gcm_6_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_6_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_6_xml.dir/build
.PHONY : valgrind_test_tls_aes128gcm_6_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_5

# Build rule for target.
valgrind_test_tls_isap_5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_5
.PHONY : valgrind_test_tls_isap_5

# fast build rule for target.
valgrind_test_tls_isap_5/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_5.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_5.dir/build
.PHONY : valgrind_test_tls_isap_5/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_5_xml

# Build rule for target.
valgrind_test_tls_isap_5_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_5_xml
.PHONY : valgrind_test_tls_isap_5_xml

# fast build rule for target.
valgrind_test_tls_isap_5_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_5_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_5_xml.dir/build
.PHONY : valgrind_test_tls_isap_5_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_5

# Build rule for target.
valgrind_test_tls_ascon_5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_5
.PHONY : valgrind_test_tls_ascon_5

# fast build rule for target.
valgrind_test_tls_ascon_5/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_5.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_5.dir/build
.PHONY : valgrind_test_tls_ascon_5/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_5_xml

# Build rule for target.
valgrind_test_tls_ascon_5_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_5_xml
.PHONY : valgrind_test_tls_ascon_5_xml

# fast build rule for target.
valgrind_test_tls_ascon_5_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_5_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_5_xml.dir/build
.PHONY : valgrind_test_tls_ascon_5_xml/fast

#=============================================================================
# Target rules for targets named test_task2_custom

# Build rule for target.
test_task2_custom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_task2_custom
.PHONY : test_task2_custom

# fast build rule for target.
test_task2_custom/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_task2_custom.dir/build.make tls/tests/CMakeFiles/test_task2_custom.dir/build
.PHONY : test_task2_custom/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_4

# Build rule for target.
valgrind_test_tls_isap_4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_4
.PHONY : valgrind_test_tls_isap_4

# fast build rule for target.
valgrind_test_tls_isap_4/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_4.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_4.dir/build
.PHONY : valgrind_test_tls_isap_4/fast

#=============================================================================
# Target rules for targets named test_task1_custom

# Build rule for target.
test_task1_custom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_task1_custom
.PHONY : test_task1_custom

# fast build rule for target.
test_task1_custom/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_task1_custom.dir/build.make tls/tests/CMakeFiles/test_task1_custom.dir/build
.PHONY : test_task1_custom/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_1

# Build rule for target.
valgrind_test_tls_aes128gcm_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_1
.PHONY : valgrind_test_tls_aes128gcm_1

# fast build rule for target.
valgrind_test_tls_aes128gcm_1/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_1.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_1.dir/build
.PHONY : valgrind_test_tls_aes128gcm_1/fast

#=============================================================================
# Target rules for targets named valgrind_test_ascon

# Build rule for target.
valgrind_test_ascon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_ascon
.PHONY : valgrind_test_ascon

# fast build rule for target.
valgrind_test_ascon/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_ascon.dir/build.make tls/tests/CMakeFiles/valgrind_test_ascon.dir/build
.PHONY : valgrind_test_ascon/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_6_xml

# Build rule for target.
valgrind_test_tls_ascon_6_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_6_xml
.PHONY : valgrind_test_tls_ascon_6_xml

# fast build rule for target.
valgrind_test_tls_ascon_6_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_6_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_6_xml.dir/build
.PHONY : valgrind_test_tls_ascon_6_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_3_xml

# Build rule for target.
valgrind_test_tls_isap_3_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_3_xml
.PHONY : valgrind_test_tls_isap_3_xml

# fast build rule for target.
valgrind_test_tls_isap_3_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_3_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_3_xml.dir/build
.PHONY : valgrind_test_tls_isap_3_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_ascon_xml

# Build rule for target.
valgrind_test_ascon_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_ascon_xml
.PHONY : valgrind_test_ascon_xml

# fast build rule for target.
valgrind_test_ascon_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_ascon_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_ascon_xml.dir/build
.PHONY : valgrind_test_ascon_xml/fast

#=============================================================================
# Target rules for targets named test_ascon

# Build rule for target.
test_ascon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ascon
.PHONY : test_ascon

# fast build rule for target.
test_ascon/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_ascon.dir/build.make tls/tests/CMakeFiles/test_ascon.dir/build
.PHONY : test_ascon/fast

#=============================================================================
# Target rules for targets named valgrind_test_hkdf

# Build rule for target.
valgrind_test_hkdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_hkdf
.PHONY : valgrind_test_hkdf

# fast build rule for target.
valgrind_test_hkdf/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_hkdf.dir/build.make tls/tests/CMakeFiles/valgrind_test_hkdf.dir/build
.PHONY : valgrind_test_hkdf/fast

#=============================================================================
# Target rules for targets named valgrind_test_aesgcm

# Build rule for target.
valgrind_test_aesgcm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_aesgcm
.PHONY : valgrind_test_aesgcm

# fast build rule for target.
valgrind_test_aesgcm/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_aesgcm.dir/build.make tls/tests/CMakeFiles/valgrind_test_aesgcm.dir/build
.PHONY : valgrind_test_aesgcm/fast

#=============================================================================
# Target rules for targets named valgrind_test_nonce

# Build rule for target.
valgrind_test_nonce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_nonce
.PHONY : valgrind_test_nonce

# fast build rule for target.
valgrind_test_nonce/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_nonce.dir/build.make tls/tests/CMakeFiles/valgrind_test_nonce.dir/build
.PHONY : valgrind_test_nonce/fast

#=============================================================================
# Target rules for targets named test_random

# Build rule for target.
test_random: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_random
.PHONY : test_random

# fast build rule for target.
test_random/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_random.dir/build.make tls/tests/CMakeFiles/test_random.dir/build
.PHONY : test_random/fast

#=============================================================================
# Target rules for targets named valgrind_test_task1_custom_xml

# Build rule for target.
valgrind_test_task1_custom_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_task1_custom_xml
.PHONY : valgrind_test_task1_custom_xml

# fast build rule for target.
valgrind_test_task1_custom_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_task1_custom_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_task1_custom_xml.dir/build
.PHONY : valgrind_test_task1_custom_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_2_xml

# Build rule for target.
valgrind_test_tls_isap_2_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_2_xml
.PHONY : valgrind_test_tls_isap_2_xml

# fast build rule for target.
valgrind_test_tls_isap_2_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_2_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_2_xml.dir/build
.PHONY : valgrind_test_tls_isap_2_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_hmac_sha2_xml

# Build rule for target.
valgrind_test_hmac_sha2_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_hmac_sha2_xml
.PHONY : valgrind_test_hmac_sha2_xml

# fast build rule for target.
valgrind_test_hmac_sha2_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_hmac_sha2_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_hmac_sha2_xml.dir/build
.PHONY : valgrind_test_hmac_sha2_xml/fast

#=============================================================================
# Target rules for targets named test_aesgcm

# Build rule for target.
test_aesgcm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_aesgcm
.PHONY : test_aesgcm

# fast build rule for target.
test_aesgcm/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_aesgcm.dir/build.make tls/tests/CMakeFiles/test_aesgcm.dir/build
.PHONY : test_aesgcm/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_2

# Build rule for target.
valgrind_test_tls_aes128gcm_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_2
.PHONY : valgrind_test_tls_aes128gcm_2

# fast build rule for target.
valgrind_test_tls_aes128gcm_2/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_2.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_2.dir/build
.PHONY : valgrind_test_tls_aes128gcm_2/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_6

# Build rule for target.
valgrind_test_tls_isap_6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_6
.PHONY : valgrind_test_tls_isap_6

# fast build rule for target.
valgrind_test_tls_isap_6/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_6.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_6.dir/build
.PHONY : valgrind_test_tls_isap_6/fast

#=============================================================================
# Target rules for targets named valgrind_test_hmac_sha2

# Build rule for target.
valgrind_test_hmac_sha2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_hmac_sha2
.PHONY : valgrind_test_hmac_sha2

# fast build rule for target.
valgrind_test_hmac_sha2/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_hmac_sha2.dir/build.make tls/tests/CMakeFiles/valgrind_test_hmac_sha2.dir/build
.PHONY : valgrind_test_hmac_sha2/fast

#=============================================================================
# Target rules for targets named test_nonce

# Build rule for target.
test_nonce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_nonce
.PHONY : test_nonce

# fast build rule for target.
test_nonce/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_nonce.dir/build.make tls/tests/CMakeFiles/test_nonce.dir/build
.PHONY : test_nonce/fast

#=============================================================================
# Target rules for targets named valgrind_test_nonce_xml

# Build rule for target.
valgrind_test_nonce_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_nonce_xml
.PHONY : valgrind_test_nonce_xml

# fast build rule for target.
valgrind_test_nonce_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_nonce_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_nonce_xml.dir/build
.PHONY : valgrind_test_nonce_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_4

# Build rule for target.
valgrind_test_tls_aes128gcm_4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_4
.PHONY : valgrind_test_tls_aes128gcm_4

# fast build rule for target.
valgrind_test_tls_aes128gcm_4/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_4.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_4.dir/build
.PHONY : valgrind_test_tls_aes128gcm_4/fast

#=============================================================================
# Target rules for targets named valgrind_test_random_xml

# Build rule for target.
valgrind_test_random_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_random_xml
.PHONY : valgrind_test_random_xml

# fast build rule for target.
valgrind_test_random_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_random_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_random_xml.dir/build
.PHONY : valgrind_test_random_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_4

# Build rule for target.
valgrind_test_tls_ascon_4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_4
.PHONY : valgrind_test_tls_ascon_4

# fast build rule for target.
valgrind_test_tls_ascon_4/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_4.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_4.dir/build
.PHONY : valgrind_test_tls_ascon_4/fast

#=============================================================================
# Target rules for targets named valgrind_test_sha2

# Build rule for target.
valgrind_test_sha2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_sha2
.PHONY : valgrind_test_sha2

# fast build rule for target.
valgrind_test_sha2/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_sha2.dir/build.make tls/tests/CMakeFiles/valgrind_test_sha2.dir/build
.PHONY : valgrind_test_sha2/fast

#=============================================================================
# Target rules for targets named valgrind_test_sha2_xml

# Build rule for target.
valgrind_test_sha2_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_sha2_xml
.PHONY : valgrind_test_sha2_xml

# fast build rule for target.
valgrind_test_sha2_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_sha2_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_sha2_xml.dir/build
.PHONY : valgrind_test_sha2_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_task1_custom

# Build rule for target.
valgrind_test_task1_custom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_task1_custom
.PHONY : valgrind_test_task1_custom

# fast build rule for target.
valgrind_test_task1_custom/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_task1_custom.dir/build.make tls/tests/CMakeFiles/valgrind_test_task1_custom.dir/build
.PHONY : valgrind_test_task1_custom/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_4_xml

# Build rule for target.
valgrind_test_tls_isap_4_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_4_xml
.PHONY : valgrind_test_tls_isap_4_xml

# fast build rule for target.
valgrind_test_tls_isap_4_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_4_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_4_xml.dir/build
.PHONY : valgrind_test_tls_isap_4_xml/fast

#=============================================================================
# Target rules for targets named test_hmac_sha2

# Build rule for target.
test_hmac_sha2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hmac_sha2
.PHONY : test_hmac_sha2

# fast build rule for target.
test_hmac_sha2/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_hmac_sha2.dir/build.make tls/tests/CMakeFiles/test_hmac_sha2.dir/build
.PHONY : test_hmac_sha2/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_6_xml

# Build rule for target.
valgrind_test_tls_isap_6_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_6_xml
.PHONY : valgrind_test_tls_isap_6_xml

# fast build rule for target.
valgrind_test_tls_isap_6_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_6_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_6_xml.dir/build
.PHONY : valgrind_test_tls_isap_6_xml/fast

#=============================================================================
# Target rules for targets named test_tls_encrypted_record

# Build rule for target.
test_tls_encrypted_record: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tls_encrypted_record
.PHONY : test_tls_encrypted_record

# fast build rule for target.
test_tls_encrypted_record/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_tls_encrypted_record.dir/build.make tls/tests/CMakeFiles/test_tls_encrypted_record.dir/build
.PHONY : test_tls_encrypted_record/fast

#=============================================================================
# Target rules for targets named test_tls_handshake

# Build rule for target.
test_tls_handshake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tls_handshake
.PHONY : test_tls_handshake

# fast build rule for target.
test_tls_handshake/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_tls_handshake.dir/build.make tls/tests/CMakeFiles/test_tls_handshake.dir/build
.PHONY : test_tls_handshake/fast

#=============================================================================
# Target rules for targets named valgrind_test_aesgcm_xml

# Build rule for target.
valgrind_test_aesgcm_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_aesgcm_xml
.PHONY : valgrind_test_aesgcm_xml

# fast build rule for target.
valgrind_test_aesgcm_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_aesgcm_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_aesgcm_xml.dir/build
.PHONY : valgrind_test_aesgcm_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_1

# Build rule for target.
valgrind_test_tls_ascon_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_1
.PHONY : valgrind_test_tls_ascon_1

# fast build rule for target.
valgrind_test_tls_ascon_1/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_1.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_1.dir/build
.PHONY : valgrind_test_tls_ascon_1/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_5_xml

# Build rule for target.
valgrind_test_tls_aes128gcm_5_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_5_xml
.PHONY : valgrind_test_tls_aes128gcm_5_xml

# fast build rule for target.
valgrind_test_tls_aes128gcm_5_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_5_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_5_xml.dir/build
.PHONY : valgrind_test_tls_aes128gcm_5_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_1_xml

# Build rule for target.
valgrind_test_tls_aes128gcm_1_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_1_xml
.PHONY : valgrind_test_tls_aes128gcm_1_xml

# fast build rule for target.
valgrind_test_tls_aes128gcm_1_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_1_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_1_xml.dir/build
.PHONY : valgrind_test_tls_aes128gcm_1_xml/fast

#=============================================================================
# Target rules for targets named test_hkdf

# Build rule for target.
test_hkdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hkdf
.PHONY : test_hkdf

# fast build rule for target.
test_hkdf/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_hkdf.dir/build.make tls/tests/CMakeFiles/test_hkdf.dir/build
.PHONY : test_hkdf/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_1_xml

# Build rule for target.
valgrind_test_tls_isap_1_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_1_xml
.PHONY : valgrind_test_tls_isap_1_xml

# fast build rule for target.
valgrind_test_tls_isap_1_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_1_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_1_xml.dir/build
.PHONY : valgrind_test_tls_isap_1_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_2_xml

# Build rule for target.
valgrind_test_tls_ascon_2_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_2_xml
.PHONY : valgrind_test_tls_ascon_2_xml

# fast build rule for target.
valgrind_test_tls_ascon_2_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_2_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_2_xml.dir/build
.PHONY : valgrind_test_tls_ascon_2_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_random

# Build rule for target.
valgrind_test_random: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_random
.PHONY : valgrind_test_random

# fast build rule for target.
valgrind_test_random/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_random.dir/build.make tls/tests/CMakeFiles/valgrind_test_random.dir/build
.PHONY : valgrind_test_random/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_2

# Build rule for target.
valgrind_test_tls_ascon_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_2
.PHONY : valgrind_test_tls_ascon_2

# fast build rule for target.
valgrind_test_tls_ascon_2/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_2.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_2.dir/build
.PHONY : valgrind_test_tls_ascon_2/fast

#=============================================================================
# Target rules for targets named valgrind_test_hkdf_xml

# Build rule for target.
valgrind_test_hkdf_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_hkdf_xml
.PHONY : valgrind_test_hkdf_xml

# fast build rule for target.
valgrind_test_hkdf_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_hkdf_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_hkdf_xml.dir/build
.PHONY : valgrind_test_hkdf_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_2_xml

# Build rule for target.
valgrind_test_tls_aes128gcm_2_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_2_xml
.PHONY : valgrind_test_tls_aes128gcm_2_xml

# fast build rule for target.
valgrind_test_tls_aes128gcm_2_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_2_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_2_xml.dir/build
.PHONY : valgrind_test_tls_aes128gcm_2_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_1

# Build rule for target.
valgrind_test_tls_isap_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_1
.PHONY : valgrind_test_tls_isap_1

# fast build rule for target.
valgrind_test_tls_isap_1/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_1.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_1.dir/build
.PHONY : valgrind_test_tls_isap_1/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_2

# Build rule for target.
valgrind_test_tls_isap_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_2
.PHONY : valgrind_test_tls_isap_2

# fast build rule for target.
valgrind_test_tls_isap_2/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_2.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_2.dir/build
.PHONY : valgrind_test_tls_isap_2/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_3_xml

# Build rule for target.
valgrind_test_tls_ascon_3_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_3_xml
.PHONY : valgrind_test_tls_ascon_3_xml

# fast build rule for target.
valgrind_test_tls_ascon_3_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_3_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_3_xml.dir/build
.PHONY : valgrind_test_tls_ascon_3_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_3

# Build rule for target.
valgrind_test_tls_ascon_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_3
.PHONY : valgrind_test_tls_ascon_3

# fast build rule for target.
valgrind_test_tls_ascon_3/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_3.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_3.dir/build
.PHONY : valgrind_test_tls_ascon_3/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_3_xml

# Build rule for target.
valgrind_test_tls_aes128gcm_3_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_3_xml
.PHONY : valgrind_test_tls_aes128gcm_3_xml

# fast build rule for target.
valgrind_test_tls_aes128gcm_3_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_3_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_3_xml.dir/build
.PHONY : valgrind_test_tls_aes128gcm_3_xml/fast

#=============================================================================
# Target rules for targets named test_sha2

# Build rule for target.
test_sha2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sha2
.PHONY : test_sha2

# fast build rule for target.
test_sha2/fast:
	$(MAKE) -f tls/tests/CMakeFiles/test_sha2.dir/build.make tls/tests/CMakeFiles/test_sha2.dir/build
.PHONY : test_sha2/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_3

# Build rule for target.
valgrind_test_tls_aes128gcm_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_3
.PHONY : valgrind_test_tls_aes128gcm_3

# fast build rule for target.
valgrind_test_tls_aes128gcm_3/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_3.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_3.dir/build
.PHONY : valgrind_test_tls_aes128gcm_3/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_5

# Build rule for target.
valgrind_test_tls_aes128gcm_5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_5
.PHONY : valgrind_test_tls_aes128gcm_5

# fast build rule for target.
valgrind_test_tls_aes128gcm_5/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_5.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_5.dir/build
.PHONY : valgrind_test_tls_aes128gcm_5/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_1_xml

# Build rule for target.
valgrind_test_tls_ascon_1_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_1_xml
.PHONY : valgrind_test_tls_ascon_1_xml

# fast build rule for target.
valgrind_test_tls_ascon_1_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_1_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_1_xml.dir/build
.PHONY : valgrind_test_tls_ascon_1_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_isap_3

# Build rule for target.
valgrind_test_tls_isap_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_isap_3
.PHONY : valgrind_test_tls_isap_3

# fast build rule for target.
valgrind_test_tls_isap_3/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_isap_3.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_isap_3.dir/build
.PHONY : valgrind_test_tls_isap_3/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_4_xml

# Build rule for target.
valgrind_test_tls_ascon_4_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_4_xml
.PHONY : valgrind_test_tls_ascon_4_xml

# fast build rule for target.
valgrind_test_tls_ascon_4_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_4_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_4_xml.dir/build
.PHONY : valgrind_test_tls_ascon_4_xml/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_ascon_6

# Build rule for target.
valgrind_test_tls_ascon_6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_ascon_6
.PHONY : valgrind_test_tls_ascon_6

# fast build rule for target.
valgrind_test_tls_ascon_6/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_ascon_6.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_ascon_6.dir/build
.PHONY : valgrind_test_tls_ascon_6/fast

#=============================================================================
# Target rules for targets named valgrind_test_tls_aes128gcm_4_xml

# Build rule for target.
valgrind_test_tls_aes128gcm_4_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind_test_tls_aes128gcm_4_xml
.PHONY : valgrind_test_tls_aes128gcm_4_xml

# fast build rule for target.
valgrind_test_tls_aes128gcm_4_xml/fast:
	$(MAKE) -f tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_4_xml.dir/build.make tls/tests/CMakeFiles/valgrind_test_tls_aes128gcm_4_xml.dir/build
.PHONY : valgrind_test_tls_aes128gcm_4_xml/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... doxygen"
	@echo "... utils"
	@echo "... ascon"
	@echo "... isap"
	@echo "... ecc_lib"
	@echo "... primitives"
	@echo "... server"
	@echo "... client"
	@echo "... valgrind_test_task2_custom"
	@echo "... valgrind_test_task2_custom_xml"
	@echo "... valgrind_test_tls_handshake"
	@echo "... valgrind_test_tls_handshake_xml"
	@echo "... valgrind_test_tls_record_layer"
	@echo "... valgrind_test_tls_record_layer_xml"
	@echo "... test_tls_record_layer"
	@echo "... valgrind_test_ecdh"
	@echo "... valgrind_test_ecdh_xml"
	@echo "... test_ecdh"
	@echo "... playback"
	@echo "... valgrind_test_tls_aes128gcm_6"
	@echo "... valgrind_test_tls_aes128gcm_6_xml"
	@echo "... valgrind_test_tls_isap_5"
	@echo "... valgrind_test_tls_isap_5_xml"
	@echo "... valgrind_test_tls_ascon_5"
	@echo "... valgrind_test_tls_ascon_5_xml"
	@echo "... test_task2_custom"
	@echo "... valgrind_test_tls_isap_4"
	@echo "... test_task1_custom"
	@echo "... valgrind_test_tls_aes128gcm_1"
	@echo "... valgrind_test_ascon"
	@echo "... valgrind_test_tls_ascon_6_xml"
	@echo "... valgrind_test_tls_isap_3_xml"
	@echo "... valgrind_test_ascon_xml"
	@echo "... test_ascon"
	@echo "... valgrind_test_hkdf"
	@echo "... valgrind_test_aesgcm"
	@echo "... valgrind_test_nonce"
	@echo "... test_random"
	@echo "... valgrind_test_task1_custom_xml"
	@echo "... valgrind_test_tls_isap_2_xml"
	@echo "... valgrind_test_hmac_sha2_xml"
	@echo "... test_aesgcm"
	@echo "... valgrind_test_tls_aes128gcm_2"
	@echo "... valgrind_test_tls_isap_6"
	@echo "... valgrind_test_hmac_sha2"
	@echo "... test_nonce"
	@echo "... valgrind_test_nonce_xml"
	@echo "... valgrind_test_tls_aes128gcm_4"
	@echo "... valgrind_test_random_xml"
	@echo "... valgrind_test_tls_ascon_4"
	@echo "... valgrind_test_sha2"
	@echo "... valgrind_test_sha2_xml"
	@echo "... valgrind_test_task1_custom"
	@echo "... valgrind_test_tls_isap_4_xml"
	@echo "... test_hmac_sha2"
	@echo "... valgrind_test_tls_isap_6_xml"
	@echo "... test_tls_encrypted_record"
	@echo "... test_tls_handshake"
	@echo "... valgrind_test_aesgcm_xml"
	@echo "... valgrind_test_tls_ascon_1"
	@echo "... valgrind_test_tls_aes128gcm_5_xml"
	@echo "... valgrind_test_tls_aes128gcm_1_xml"
	@echo "... test_hkdf"
	@echo "... valgrind_test_tls_isap_1_xml"
	@echo "... valgrind_test_tls_ascon_2_xml"
	@echo "... valgrind_test_random"
	@echo "... valgrind_test_tls_ascon_2"
	@echo "... valgrind_test_hkdf_xml"
	@echo "... valgrind_test_tls_aes128gcm_2_xml"
	@echo "... valgrind_test_tls_isap_1"
	@echo "... valgrind_test_tls_isap_2"
	@echo "... valgrind_test_tls_ascon_3_xml"
	@echo "... valgrind_test_tls_ascon_3"
	@echo "... valgrind_test_tls_aes128gcm_3_xml"
	@echo "... test_sha2"
	@echo "... valgrind_test_tls_aes128gcm_3"
	@echo "... valgrind_test_tls_aes128gcm_5"
	@echo "... valgrind_test_tls_ascon_1_xml"
	@echo "... valgrind_test_tls_isap_3"
	@echo "... valgrind_test_tls_ascon_4_xml"
	@echo "... valgrind_test_tls_ascon_6"
	@echo "... valgrind_test_tls_aes128gcm_4_xml"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

